name: Update Release 2.0

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create ZIP with only necessary files
        run: |
          # Buat ZIP yang include semua file needed, exclude .github
          zip -r Mentari.zip . \
            -i "*.js" "*.html" "*.json" "*.png" "*.md" \
            -x "*.git*" "*.github*" ".github/*" ".github/workflows/*"

      - name: Update tag 2.0 to latest commit
        run: |
          git tag -f "2.0"
          git push origin -f "2.0"

      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "2.0"
          name: "Mentari v2.0"
          body: |
            Update:

            • hiding discussion forums that have no topics
            • added a notification feature for lecturer replies  
            • added update notifications
            • can select more than one prompt format in the chatbot

            Small update:

            • fixed an error in the extension

            10/3/2025 - User Status Fixed.

            🔄 Auto-updated: ${{ github.event.head_commit.timestamp }}
          files: |
            Mentari.zip
          draft: false
          prerelease: false
          generate_release_notes: false
          replace_assets: true
